#!/usr/bin/env python3
"""Export cached score responses for the six demo profiles.

Writes frontend/src/lib/_mock_data.json so the frontend can serve a working demo
even if the backend is unreachable mid-presentation (NEXT_PUBLIC_DEMO_MODE=true).
Regenerated by bootstrap.sh after training so the cache always matches the model.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_ROOT = SCRIPT_DIR.parent
REPO_ROOT = BACKEND_ROOT.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.ml.registry import registry  # noqa: E402
from app.services.mock_profiles import MOCK_PROFILES  # noqa: E402
from app.services.pipeline import run_scoring  # noqa: E402

OUT = REPO_ROOT / "frontend" / "src" / "lib" / "_mock_data.json"
_PROFILE_KEYS = (
    "id", "display_name", "headline", "city", "archetype", "business_type",
    "requested_amount_pkr", "purpose", "applicant", "features", "bill_fields",
    "expected_band",
)


def main() -> None:
    registry.load()
    if not registry.loaded:
        raise SystemExit(f"Model not loaded: {registry.error}")
    bundles = []
    for p in MOCK_PROFILES:
        result = run_scoring(dict(p["features"]), applicant_id=p["id"], archetype_hint=p["archetype"])
        result.pop("_features_used", None)
        bundles.append({"profile": {k: p[k] for k in _PROFILE_KEYS}, "score": result})
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(bundles, indent=1), encoding="utf-8")
    print(f"[demo-cache] wrote {len(bundles)} bundles -> {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
