"""Six hand-built demo profiles. Each is a complete raw-signal set (except Zubair,
who deliberately has no transaction history so the partial-data path is exercised).
Loaded by GET /api/v1/mock/profiles and used to render the downloadable sample
files in backend/data/samples/.
"""
from __future__ import annotations

from typing import Any

# feature dicts are partial; anything omitted is imputed at population medians.
MOCK_PROFILES: list[dict[str, Any]] = [
    {
        "id": "ayesha-lahore-tailoring",
        "display_name": "Ayesha",
        "headline": "Lahore tailoring, strong bills, thin cashflow",
        "city": "Lahore",
        "archetype": "home_based_producer",
        "business_type": "Tailoring & stitching",
        "requested_amount_pkr": 60000,
        "purpose": "Buy a second industrial sewing machine",
        "applicant": {
            "full_name": "Ayesha Bibi",
            "cnic": "35202-1234567-8",
            "phone": "0301-2345678",
            "city": "Lahore",
            "archetype": "home_based_producer",
            "business_type": "Tailoring & stitching",
            "dependents_count": 3,
            "has_fixed_premises": False,
        },
        "features": {
            "utility_on_time_ratio": 0.92,
            "utility_avg_days_late": 2.0,
            "utility_bill_volatility": 0.18,
            "utility_months_observed": 12,
            "utility_disconnection_events": 0,
            "monthly_inflow_pkr": 46000,
            "monthly_outflow_pkr": 33000,
            "net_cashflow_ratio": 0.28,
            "cashflow_volatility": 0.35,
            "income_trend_slope": 0.02,
            "zero_balance_days_ratio": 0.14,
            "balance_floor_ratio": 0.11,
            "p2p_velocity": 7,
            "p2p_unique_counterparties": 6,
            "counterparty_concentration_hhi": 0.22,
            "merchant_inflow_share": 0.52,
            "txn_frequency_monthly": 41,
            "mobile_topup_regularity": 0.7,
            "expense_to_income_ratio": 0.66,
            "savings_rate": 0.19,
            "committee_participation": 1,
            "wallet_tenure_months": 28,
            "business_age_months": 54,
            "dependents_count": 3,
            "has_fixed_premises": 0,
            "sim_tenure_months": 44,
        },
        "bill_fields": {"provider": "LESCO", "units_consumed": 210, "current_charges": 5400, "arrears": 0},
        "expected_band": "MEDIUM",
    },
    {
        "id": "bilal-karachi-kiryana",
        "display_name": "Bilal",
        "headline": "Karachi kiryana, high volume, volatile",
        "city": "Karachi",
        "archetype": "kiryana_merchant",
        "business_type": "Neighbourhood grocery",
        "requested_amount_pkr": 120000,
        "purpose": "Stock up wholesale before Ramzan",
        "applicant": {
            "full_name": "Bilal Ahmed",
            "cnic": "42101-7654321-1",
            "phone": "0321-9876543",
            "city": "Karachi",
            "archetype": "kiryana_merchant",
            "business_type": "Neighbourhood grocery",
            "dependents_count": 5,
            "has_fixed_premises": True,
        },
        "features": {
            "utility_on_time_ratio": 0.74,
            "utility_avg_days_late": 7.0,
            "utility_bill_volatility": 0.34,
            "utility_months_observed": 12,
            "utility_disconnection_events": 0,
            "monthly_inflow_pkr": 240000,
            "monthly_outflow_pkr": 210000,
            "net_cashflow_ratio": 0.125,
            "cashflow_volatility": 0.42,
            "income_trend_slope": 0.01,
            "zero_balance_days_ratio": 0.16,
            "balance_floor_ratio": 0.08,
            "p2p_velocity": 18,
            "p2p_unique_counterparties": 9,
            "counterparty_concentration_hhi": 0.18,
            "merchant_inflow_share": 0.74,
            "txn_frequency_monthly": 128,
            "mobile_topup_regularity": 0.55,
            "expense_to_income_ratio": 0.76,
            "savings_rate": 0.12,
            "committee_participation": 0,
            "wallet_tenure_months": 33,
            "business_age_months": 96,
            "dependents_count": 5,
            "has_fixed_premises": 1,
            "sim_tenure_months": 61,
        },
        "bill_fields": {"provider": "K-Electric", "units_consumed": 560, "current_charges": 18400, "arrears": 0},
        "expected_band": "HIGH",
    },
    {
        "id": "farhan-rawalpindi-ridehailing",
        "display_name": "Farhan",
        "headline": "Rawalpindi ride-hailing, steady but overextended",
        "city": "Rawalpindi",
        "archetype": "ride_hailing_driver",
        "business_type": "Careem / inDrive driver",
        "requested_amount_pkr": 85000,
        "purpose": "Car maintenance and new tyres",
        "applicant": {
            "full_name": "Farhan Khan",
            "cnic": "37405-2223334-5",
            "phone": "0333-4445556",
            "city": "Rawalpindi",
            "archetype": "ride_hailing_driver",
            "business_type": "Careem / inDrive driver",
            "dependents_count": 4,
            "has_fixed_premises": False,
        },
        "features": {
            "utility_on_time_ratio": 0.68,
            "utility_avg_days_late": 9.0,
            "utility_bill_volatility": 0.29,
            "utility_months_observed": 9,
            "utility_disconnection_events": 0,
            "monthly_inflow_pkr": 62000,
            "monthly_outflow_pkr": 56000,
            "net_cashflow_ratio": 0.097,
            "cashflow_volatility": 0.31,
            "income_trend_slope": -0.03,
            "zero_balance_days_ratio": 0.24,
            "balance_floor_ratio": 0.05,
            "p2p_velocity": 11,
            "p2p_unique_counterparties": 7,
            "counterparty_concentration_hhi": 0.14,
            "merchant_inflow_share": 0.61,
            "txn_frequency_monthly": 95,
            "mobile_topup_regularity": 0.6,
            "expense_to_income_ratio": 0.85,
            "savings_rate": 0.07,
            "committee_participation": 0,
            "wallet_tenure_months": 26,
            "business_age_months": 30,
            "dependents_count": 4,
            "has_fixed_premises": 0,
            "sim_tenure_months": 38,
        },
        "bill_fields": {"provider": "IESCO", "units_consumed": 340, "current_charges": 8600, "arrears": 900},
        "expected_band": "HIGH",
    },
    {
        "id": "nasreen-multan-homefood",
        "display_name": "Nasreen",
        "headline": "Multan home food, committee saver",
        "city": "Multan",
        "archetype": "home_based_producer",
        "business_type": "Home food preparation",
        "requested_amount_pkr": 45000,
        "purpose": "Commercial fridge and prep tables",
        "applicant": {
            "full_name": "Nasreen Akhtar",
            "cnic": "36302-9988776-4",
            "phone": "0300-1122334",
            "city": "Multan",
            "archetype": "home_based_producer",
            "business_type": "Home food preparation",
            "dependents_count": 2,
            "has_fixed_premises": False,
        },
        "features": {
            "utility_on_time_ratio": 0.98,
            "utility_avg_days_late": 0.0,
            "utility_bill_volatility": 0.12,
            "utility_months_observed": 12,
            "utility_disconnection_events": 0,
            "monthly_inflow_pkr": 52000,
            "monthly_outflow_pkr": 34000,
            "net_cashflow_ratio": 0.346,
            "cashflow_volatility": 0.19,
            "income_trend_slope": 0.05,
            "zero_balance_days_ratio": 0.05,
            "balance_floor_ratio": 0.18,
            "p2p_velocity": 8,
            "p2p_unique_counterparties": 7,
            "counterparty_concentration_hhi": 0.16,
            "merchant_inflow_share": 0.58,
            "txn_frequency_monthly": 47,
            "mobile_topup_regularity": 0.82,
            "expense_to_income_ratio": 0.58,
            "savings_rate": 0.31,
            "committee_participation": 1,
            "wallet_tenure_months": 40,
            "business_age_months": 72,
            "dependents_count": 2,
            "has_fixed_premises": 0,
            "sim_tenure_months": 66,
        },
        "bill_fields": {"provider": "MEPCO", "units_consumed": 180, "current_charges": 4200, "arrears": 0},
        "expected_band": "LOW",
    },
    {
        "id": "imran-faisalabad-dailywage",
        "display_name": "Imran",
        "headline": "Faisalabad daily wage, seasonal gaps",
        "city": "Faisalabad",
        "archetype": "daily_wage_worker",
        "business_type": "Construction labour",
        "requested_amount_pkr": 40000,
        "purpose": "Tools and monsoon-season buffer",
        "applicant": {
            "full_name": "Imran Ali",
            "cnic": "33100-4455667-9",
            "phone": "0345-6677889",
            "city": "Faisalabad",
            "archetype": "daily_wage_worker",
            "business_type": "Construction labour",
            "dependents_count": 6,
            "has_fixed_premises": False,
        },
        "features": {
            "utility_on_time_ratio": 0.44,
            "utility_avg_days_late": 19.0,
            "utility_bill_volatility": 0.42,
            "utility_months_observed": 7,
            "utility_disconnection_events": 2,
            "monthly_inflow_pkr": 33000,
            "monthly_outflow_pkr": 31500,
            "net_cashflow_ratio": 0.045,
            "cashflow_volatility": 0.55,
            "income_trend_slope": -0.07,
            "zero_balance_days_ratio": 0.45,
            "balance_floor_ratio": 0.02,
            "p2p_velocity": 4,
            "p2p_unique_counterparties": 3,
            "counterparty_concentration_hhi": 0.41,
            "merchant_inflow_share": 0.12,
            "txn_frequency_monthly": 21,
            "mobile_topup_regularity": 0.3,
            "expense_to_income_ratio": 0.95,
            "savings_rate": 0.02,
            "committee_participation": 0,
            "wallet_tenure_months": 14,
            "business_age_months": 18,
            "dependents_count": 6,
            "has_fixed_premises": 0,
            "sim_tenure_months": 20,
        },
        "bill_fields": {"provider": "FESCO", "units_consumed": 260, "current_charges": 6400, "arrears": 3600},
        "expected_band": "VERY_HIGH",
    },
    {
        "id": "zubair-peshawar-autoparts",
        "display_name": "Zubair",
        "headline": "Peshawar auto parts, new business no history",
        "city": "Peshawar",
        "archetype": "kiryana_merchant",
        "business_type": "Auto-parts retail",
        "requested_amount_pkr": 70000,
        "purpose": "Initial inventory for a new shop",
        "applicant": {
            "full_name": "Zubair Gul",
            "cnic": "17301-3344556-7",
            "phone": "0311-2233445",
            "city": "Peshawar",
            "archetype": "kiryana_merchant",
            "business_type": "Auto-parts retail",
            "dependents_count": 3,
            "has_fixed_premises": True,
        },
        # DELIBERATELY only a bill-derived slice -- no transaction log.
        "features": {
            "utility_on_time_ratio": 0.83,
            "utility_avg_days_late": 4.0,
            "utility_bill_volatility": 0.24,
            "utility_months_observed": 4,
            "utility_disconnection_events": 0,
            "business_age_months": 3,
            "has_fixed_premises": 1,
            "dependents_count": 3,
            "wallet_tenure_months": 5,
            "sim_tenure_months": 9,
        },
        "bill_fields": {"provider": "PESCO", "units_consumed": 300, "current_charges": 7200, "arrears": 0},
        "expected_band": "MEDIUM",
    },
]

MOCK_BY_ID = {p["id"]: p for p in MOCK_PROFILES}
